### PR TITLE
8051 Instruction set

### PR DESCRIPTION
**Pull request by a-rmz**
I added (if I'm not wrong) the whole instruction set of the 8051.

### CODE REVIEW

**Comment by oliverkeeble** [comment]
Once again, thanks! This is awesome! I'll merge this later unless you need to add something.

**Comment by a-rmz** [comment]
My pleasure! :) 
I think I'll just modify a couple things on the README to clarify the support of the AT89S52.

**Comment by oliverkeeble** [comment]
Sounds good, also you should probably rename the grammar file to something more generic like `assembly.cson`. Thanks again :-)

**Comment by a-rmz** [comment]
Sure, no problem.

**Comment by a-rmz** [comment]
Sure, no problem. Also, when I have some time I'll add some more snippets.

**Comment by oliverkeeble** [comment]
Great! Also, maybe there should be a wiki page for snippets and just a few examples in the readme. Thoughts?

**Comment by a-rmz** [comment]
Yes! My original idea (on my fork) was to do a wiki; I it would be useful.

**Comment by a-rmz** [comment]
I have no idea on how to do that, but, if you don't mind, I'll try to start the wiki.

**Comment by oliverkeeble** [comment]
Oh, I've already created the pages. Additions are always welcome. I got a bit enthusiastic :-)

**Comment by a-rmz** [comment]
Yeah, I saw haha. Just... I can't edit on your repo, so either you add me as collaborator or you can add everything yourself.

**Comment by oliverkeeble** [comment]
Oh, of course. You've clearly got more experience than me here (not difficult).

**Comment by a-rmz** [comment]
Wel... ahem... not that much, but I don't see any `edit` option, so I assume that hahaha.

**Comment by oliverkeeble** [comment]
Right, I found the button. You're now a contributor. You've added a whole new instruction set, nobody can deny it.

**Comment by a-rmz** [comment]
Thanks! I appreciate that. :)
So, without any further prelude, I'll merge the pull request.

**Comment by a-rmz** [comment]
One more thing! About the package version. Would you like this to be version 0.7.0?

**Comment by oliverkeeble** [comment]
Oh yeah, of course! A new instruction set is definitely more than a patch :-)

**Comment by a-rmz** [comment]
Ohhh, damn it. Okay, I wasn't sure about that. So... do you want me to restore the previous one?

**Comment by oliverkeeble** [comment]
No worries, I just dealt with it :-)

**Comment by a-rmz** [comment]
I'm sorry haha. I got the wiki running aaaand just missing to remove the snippets on the README.

**Comment by oliverkeeble** [comment]
No need to be sorry, I just learned git revert. It's good practice :-)

**Comment by a-rmz** [comment]
I think the best thing will be finding a way to add the snippets to the package itself. I haven't worked with Atom packages before, so I'm not quite sure on how to do that, but I'll investigate and see what I can find.

**Comment by oliverkeeble** [comment]
Looks to me like creating a snippets folder and putting some CSON in it should do the trick.

**Comment by a-rmz** [comment]
Hmmm... clever idea. Check out the new README btw.

**Comment by oliverkeeble** [comment]
Yeah, looks good! I just added a missing space to the to do list, Markdown seems a bit fussy.

**Comment by a-rmz** [comment]
Cool. I tried adding a snippets folder, and it worked haha.

**Pull request merged**
